### ISSUE TITLE
Some Contributors have inaccurate sort_names, which "breaks" author faceting

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/content_server#108]
I've noticed this specifically in Instant Classics, but it's likely impacting other feeds as well.

Some authors have sort names that aren't last-name-first (eg, Alan Nourse, sort_name: Alan E. Nourse or Austin Hall, sort_name: Austin Hall). This makes author-specific faceting inaccurate and unhelpful.

**Comment by leonardr** [comment]
I see this problem in the original Feedbooks import on the production content server, but not in a fresh import. I'm going to say the problem has been fixed (either on Feedbooks's side or ours).
