### ISSUE TITLE
Create a FeedBooks-specific Classifier

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/content_server#117]
Since we're going to keep working with FeedBooks, we may want to create a FeedBooksClassifier at some point. Their identifiers have subject information that can be more detailed or direct than their subject names.

Some examples:
 - `FBFIC027040 - Gothic` and `FBFIC024010N - Gothic` are both gothic fiction, but "Gothic" alone is too general a keyword to make the assumption overall.
 - `FBDRA011000N - Greek` is a Greek drama, while `FBJUV022020 - Greek & Roman` is a juvenile work with Greek / Roman aspects.
 - `FBFIC004030N - Modern (<1799)` and `FBFIC014040N - Modern (<1799)` are fiction. `FBPOE009000N - Modern (<1799)` is poetry, and `FBDRA050000N - Modern (<1799)` is drama.
 - So on and so forth.

This was initially detailed in NYPL-Simplified/server_core#451.

**Comment by leonardr** [comment]
Moved into https://github.com/NYPL-Simplified/server_core/issues/834 as part of https://github.com/NYPL-Simplified/content_server/issues/143.
