### ISSUE TITLE
Investigate faulty classification of The Magic Fishbone

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/content_server#123]
Right now the FeedBooks Work _The Magic Fishbone_ by Charles Dickens (urn=http://www.feedbooks.com/book/6634) is classified as Nonfiction in the alpha db, even though it should be in the Fiction, Short Stories, and Fantasy genres. There aren't any categories at all on its origin OPDS feed: http://www.feedbooks.com/book/6634.atom.

After some investigation, it looks like any FeedBooks Work that didn't have any `category` defined in its OPDS feed has been imported under the Nonfiction genre. Here are a couple more examples:
- http://www.feedbooks.com/book/5106.atom
- http://www.feedbooks.com/book/5109.atom
- http://www.feedbooks.com/book/2943.atom

I made some manual changes to the most obvious works (to me) in the  CSV import as a fast fix this in the Instant Classics feeds, but when we're using CustomLists that won't be possible anymore. When we reimport the FeedBooks Works, we should fix this.

**Comment by courte** [comment]
Oh, it looks like many of Shakespeare's historical plays are legit categorized as nonfiction, too, so that's contributing: http://www.feedbooks.com/book/3027.atom. I'm going to leave those alone.

**Comment by leonardr** [comment]
Moved to https://github.com/NYPL-Simplified/server_core/issues/837.
