### ISSUE TITLE
Content server incorrectly returning collections

### ISSUE THREAD

**Issue by jonathangreen** [NYPL-Simplified/content_server#142]
Importing the 'Instant Classics' collection from this OPDS feed: 
http://oacontent.librarysimplified.org/works/lists/Instant%20Classics

Should only be importing ~5000 books, but my imports are actually pulling in 50K books.

**Comment by jonathangreen** [comment]
Going this deep into the collection should be empty, but it is still returning books: 
http://oacontent.librarysimplified.org/?available=always&lane=All+books+from+Instant+Classics&after=10000&order=added&collection=full&size=50

**Comment by leonardr** [comment]
Closing as per https://github.com/NYPL-Simplified/content_server/issues/143.

This problem is present in content server-specific code, so running the content server on top of a regular circulation manager should solve it.
