### ISSUE TITLE
Update DirectoryImportScript to accept a CSV file

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/content_server#19]
Update DirectoryImportScript to use a supplemental CSV file with EPUB information if necessary.

[Jira SIM-62](https://jira.nypl.org/browse/SIM-62)

**Comment by leonardr** [comment]
In theory this is still a useful feature, but we've had good luck convincing sources of free content to go with OPDS (which we can import) rather than handing us ZIP files with metadata/covers/EPUBs.
