### ISSUE TITLE
Plympton books don't have authors in OPDS

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/content_server#34]

**Comment by aslagle** [comment]
I think the problem here is that the content server hasn't consulted the metadata wrangler to get the authors' display names. There are periods after the author names in these editions, but the metadata wrangler should be able to handle that. The metadata wrangler needs to be fixed before we can try it.

**Comment by leonardr** [comment]
We need a content server script that finds all authors who have sort name but not display name (or vice versa) and asks the metadata wrangler to find the other one.

**Comment by leonardr** [comment]
This will happen normally during an OPDS import if this information is missing and a metadata wrangler integration is present. If there is no metadata wrangler integration we'll make a best-effort attempt locally, which is generally good enough.
