### ISSUE TITLE
Authors of Plympton books end with periods; most shouldn't

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/content_server#52]
The author names we get from Plympton end with periods, e.g. "James, Henry." The only one whose name should actually end with a period is "Wells, H.G.". This causes problems when the name is "normalized" to "Henry. James". You can see the results on the Open Ebooks site.

That period needs to be stripped out on import, and the data already in the content server and Open Ebooks databases needs to be fixed.

**Comment by aslagle** [comment]
Also, the publisher we get has an extra comma - "Recovering the Classics,"

**Comment by leonardr** [comment]
AND, the descriptions of Plympton books look like this:

"This is a description of the book."--

Which makes me think it looked like this at some point:

"This is a description of the book."--Book Describers Weekly

And it should either continue to look like that, or it should look like:

This is a description of the book.

**Comment by leonardr** [comment]
The `name_tidy` function in `core` solves this problem.

The description problems are not serious enough to need a systematic approach IMO -- it's a couple bad descriptions that can be fixed in specific datasets or upstream.
