### ISSUE TITLE
standard ebooks OPDS import doesn't work reliably

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/content_server#56]
The simplest way to address this is to stick a real Standard Ebooks OPDS feed into core/tests/files/opds, and write a test that uses OPDSImporter and ensures that everything is imported and mirrored properly.

**Comment by aslagle** [comment]
This is mostly done but the imported books seem to be missing covers.

**Comment by leonardr** [comment]
This seems pretty reliable now.
