### ISSUE TITLE
Maintain original distributor when importing open-access books from OA content server

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/content_server#59]
When you import a book from the content server into the circulation manager, the license source for the new book is the OA content server itself. Instead, the original license source should be brought in through the OPDS feed.

Without this code, a Gutenberg book will never be replaced by a higher-quality edition of the same book from a different source.

**Comment by aslagle** [comment]
I think the license pool for the new book has the correct data source already, but the resource for the open access download link has the OA content server.

**Comment by leonardr** [comment]
Ah, OK, that should be easier to fix and sounds like a problem on the circulation manager side.
