### ISSUE TITLE
Show licensing information in OPDS feeds

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/content_server#67]
The content server OPDS feeds don't list the licensing information it has for every book. It should be in a dc:rights stanza.

**Comment by aslagle** [comment]
The OPDS 1.1 spec says to use atom:rights, but that only works for rights that apply to the whole entry.

**Comment by leonardr** [comment]
I talked with Hadrien about this. He agrees the best way to handle this is to put a dc:rights tag inside each link tag, and only use atom:rights if the rights are identical for every acquisition method.

**Comment by leonardr** [comment]
Replaced by https://github.com/NYPL-Simplified/server_core/issues/835.
