### ISSUE TITLE
Convert full-size SVGs to PNG

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/content_server#68]
See for example http://oacontent.alpha.librarysimplified.org/lookup?urn=http://www.gutenberg.org/ebooks/20270

```
  <link href="http://book-covers.nypl.org/Standard%20Ebooks/URI/https%3A//standardebooks.org/ebooks/joseph-conrad/heart-of-darkness/cover.svg" type="image/png" rel="http://opds-spec.org/image"/>
    <link href="http://book-covers.nypl.org/Standard%20Ebooks/URI/https%3A//standardebooks.org/ebooks/joseph-conrad/heart-of-darkness/cover-thumbnail.jpg" type="image/jpeg" rel="http://opds-spec.org/image/thumbnail"/>
```   

I checked and the cover image is in fact a SVG file. I'm not 100% sold on this, and it doesn't matter for our purposes because our clients don't use the full-size images, but I feel like we should convert the original image before uploading it to S3.

**Comment by jce1028** [comment]
Android does not currently support SVG so this makes sense.

On Fri, May 27, 2016 at 8:33 AM, Leonard Richardson <
notifications@github.com> wrote:

> See for example
> http://oacontent.alpha.librarysimplified.org/lookup?urn=http://www.gutenberg.org/ebooks/20270
>
>   <link href="http://book-covers.nypl.org/Standard%20Ebooks/URI/https%3A//standardebooks.org/ebooks/joseph-conrad/heart-of-darkness/cover.svg" type="image/png" rel="http://opds-spec.org/image"/>
>     <link href="http://book-covers.nypl.org/Standard%20Ebooks/URI/https%3A//standardebooks.org/ebooks/joseph-conrad/heart-of-darkness/cover-thumbnail.jpg" type="image/jpeg" rel="http://opds-spec.org/image/thumbnail"/>
>
> I checked and the cover image is in fact a SVG file. I'm not 100% sold on
> this, and it doesn't matter for our purposes because our clients don't use
> the full-size images, but I feel like we should convert the original image
> before uploading it to S3.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NYPL-Simplified/content_server/issues/68>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFBP214mz9pfLVgyg_Js0bEFSQ4m-0Jiks5qFuSFgaJpZM4IodQD>
> .
>



-- 
Regards,
James

www.linkedin.com/in/jamesenglish
http://about.me/jce1028
