### ISSUE TITLE
Parsing error in marc.py for pubyear

### ISSUE THREAD

**Issue by swandog30** [NYPL-Simplified/content_server#79]
The trailing period on line 32 is causing parsing errors with the marc records I'm testing with.

`issued_year = datetime.datetime.strptime(record.pubyear(), "%Y.")`

I think it's unnecessary or a typo. The date format for that 264 field doesn't contain any periods, possibly a - but that's optional.

**Comment by aslagle** [comment]
Thanks for pointing this out. We've only used this code with one marc file so far, and it had a lot of trailing punctuation that was probably wrong.

**Comment by swandog30** [comment]
Ok, cool.  If I run into other issues I'll fix up what I can and do a pull request if thats helpful.

**Comment by leonardr** [comment]
Closed by https://github.com/NYPL-Simplified/server_core/pull/836
